language: rust

matrix:
  include:
    - os: linux
      rust: stable
      env: TARGET=arm-unknown-linux-gnueabihf
      addons:
        apt:
          packages:
            - gcc-arm-linux-gnueabihf
            - libc6-armhf-cross
            - libc6-dev-armhf-cross
    - os: linux
      rust: stable
      env: TARGET=x86_64-unknown-linux-gnu

before_install:
  - export PATH="$PATH:$HOME/.cargo/bin"
  - curl 'https://sh.rustup.rs' -sSf | sh
  - rustup target add "$TARGET"
  - if [ "$TARGET" = 'arm-unknown-linux-gnueabihf']; then printf '[target.%s]\nlinker=%s\n' "$TARGET" 'arm-linux-gnueabihf-gcc' >> "$HOME/.cargo/config"; fi

script:
  - cargo build --verbose --target="$TARGET"
  - cargo test --verbose --target="$TARGET"
