language: rust

matrix:
  include:
    - os: linux
      rust: stable
      env: TARGET=x86_64-unknown-linux-gnu

rust: stable

script:
  - cargo build --verbose --target="$TARGET"
  - cargo test --verbose --target="$TARGET"
