environment:
  CAN_RELEASE: true
  RUST_VERSION: 1.13.0
  TARGET: x86_64-pc-windows-gnu
  SEC_GH_API_KEY:
    secure: rTifpMhoPie2JusCTOo6BlLMPzsuLgVkzbM0cQnD9TboCvjaXI+4xx/Zr6lkOQ3r

install:
  - ps: choco install rust
  - ps: choco install nodejs
  - ps: $env:Path = [System.Environment]::GetEnvironmentVariable("Path","Machine") + ";" + [System.Environment]::GetEnvironmentVariable("Path","User")
  - ps: rustc '--version'
  - ps: cargo '--version'
  - ps: node '--version'
  - ps: npm '--version'

build_script:
  - C:\msys64\usr\bin\bash.exe '-c' 'if [ -z "$APPVEYOR_REPO_TAG_NAME" ]; then cargo build --target="$TARGET"; else cargo build --release --target="$TARGET"; fi'
  - ps: Tree 'target'

after_build:
  - C:\Python35\python.exe release.py
