environment:
  CAN_RELEASE: true
  RUST_VERSION: 1.13.0
  TARGET: x86_64-pc-windows-gnu
  SEC_GH_API_KEY:
    secure: rTifpMhoPie2JusCTOo6BlLMPzsuLgVkzbM0cQnD9TboCvjaXI+4xx/Zr6lkOQ3r

install:
  - ps: Start-FileDownload "https://static.rust-lang.org/dist/rust-${env:RUST_VERSION}-${env:TARGET}.exe"
  - ps: Start-Process -FilePath "rust-${env:RUST_VERSION}-${env:TARGET}.exe" -ArgumentList "/VERYSILENT /NORESTART /DIR='C:\Program Files\Rust'"

before_build:
  - ps: if ( $env:APPVEYOR_REPO_TAG ) { Start-Process -FilePath 'C:\Program Files\Rust\cargo' -ArgumentList "build --release --target=${env:TARGET}" } else { Start-Process -FilePath 'C:\Program Files\Rust\cargo' -ArgumentList "build --target=${env:TARGET}" }

build: false

after_build:
  - ps: if ( $env:APPVEYOR_REPO_TAG ) { Start-Process -FilePath 'C:\Python35\python' -ArgumentList 'release.py' }
