environment:
  CAN_RELEASE: true
  RUST_VERSION: 1.13.0
  TARGET: x86_64-pc-windows-gnu
  SEC_GH_API_KEY:
    secure: rTifpMhoPie2JusCTOo6BlLMPzsuLgVkzbM0cQnD9TboCvjaXI+4xx/Zr6lkOQ3r

install:
  - ps: Start-Process -FilePath 'choco' -ArgumentList 'install rust'
  - ps: Start-Process -FilePath 'rustc' -ArgumentList '--version'
  - ps: Start-Process -FilePath 'cargo' -ArgumentList '--version'

build_script:
  - ps: if ( $env:APPVEYOR_REPO_TAG ) { Start-Process -FilePath 'cargo' -ArgumentList "build --release --target=${env:TARGET}" } else { Start-Process -FilePath 'cargo' -ArgumentList "build --target=${env:TARGET}" }
  - ps: Tree 'target'

after_build:
  - ps: if ( $env:APPVEYOR_REPO_TAG ) { Start-Process -FilePath 'C:\Python35\python.exe' -ArgumentList 'release.py' }
