[package]
name = "stabping"
version = "0.1.0"
authors = ["icasdri <icasdri@gmail.com>"]
build = "build.rs"

[dependencies]
time = "0.1"
chrono = "0.2"
rustc-serialize = "0.3"
ws = "*"
iron = "*"
router = "*"
mount = "*"
